// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrateNodeDto } from "./MigrateNodeDto";

export type MigrateRequest = { session_key: string, nodes: Array<MigrateNodeDto>, active_leaf: string | null, };
