// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrateNodeDto = { id: string, parent_id: string | null, role: string, content: string, timestamp: string | null, };
