// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTreeNodeDto } from "./SessionTreeNodeDto";

export type SessionTreeDto = { session_key: string, nodes: Array<SessionTreeNodeDto>, active_leaf: string | null, session_persistence: boolean, };
